### ISSUE TITLE
Cannot get access to Openslr

### ISSUE THREAD

**Issue by JiajunHe1025** [Mashiro009/slidespeech_dl#2]
https://www.[openslr.org](https://www.openslr.org/144/)/144/
![image](https://github.com/Mashiro009/slidespeech_dl/assets/92374261/3c61a2f3-9b93-41fd-8384-437f272d22c9) 
and aslo https://modelscope.cn/datasets/speech_asr/SlideSpeech/summary is also not available...

**Comment by Mashiro009** [comment]
Due to some reasons, quick downloading is unavailable. Please use the current repository's scripts to download the corpus.
