### ISSUE TITLE
Scripts to compute U-WER, B-WER, Recall

### ISSUE THREAD

**Issue by zsLin177** [Mashiro009/slidespeech_dl#5]
Hello,

Thanks for releasing the dataset. I am conducting some experiments based on your dataset and I am curious about the calculations for U-WER, B-WER, and Recall. Could you please provide the script for these calculations? 🙏

**Comment by Mashiro009** [comment]
Hello,

You can refer to this [Contextualized Streaming End-to-End Speech Recognition with Trie-Based Deep Biasing and Shallow Fusion](https://arxiv.org/pdf/2104.02194) and [github](https://github.com/facebookresearch/fbai-speech/tree/main/is21_deep_bias) to calculate the U-WER, B-WER. The scripts for calculating Recall needs to be organized later. Thank you for your interest in our work.

**Comment by zsLin177** [comment]
Thank you for your help. I am actively learning and using your data, and I look forward to seeing the scripts for calculating Recall.

**Comment by Mashiro009** [comment]
We provide the demo scripts for calculating Recall, U-WER, B-WER, WER. Thank you for your interest in our work.
https://github.com/Mashiro009/slidespeech_dl/tree/a1f9af4abaa106c68b3257f021b0f945080e918c/cal_recall_demo#readme
